#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive dotbot
git submodule update --init --recursive dotbot-brew
git submodule update --init --recursive packer.nvim
git submodule update --init --recursive .oh-my-zsh
git submodule update --init --recursive .oh-my-zsh
git submodule update --init --recursive .oh-my-zsh-custom/plugins/fzf-zsh-plugin
git submodule update --init --recursive .oh-my-zsh-custom/plugins/zsh-autosuggestions
git submodule update --init --recursive .oh-my-zsh-custom/themes/powerlevel10k

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brew -c "${CONFIG}" "${@}"
